services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

#  worker:
#    image: video-processing-worker:latest
#    container_name: video-processing-worker
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_RABBITMQ_PORT: 5672
#      SPRING_RABBITMQ_USERNAME: guest
#      SPRING_RABBITMQ_PASSWORD: guest
#      APP_STORAGE_LOCAL_PATH: ${APP_STORAGE_LOCAL_PATH:-/data}
#    volumes:
#      - ${APP_STORAGE_LOCAL_PATH:-./data}:/data

volumes:
  rabbitmq_data:
#  worker_data:
