spring:
  application:
    name: hackaton-video-processing-worker-fase5

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  rabbit:
    processing-queue: video.processing.queue
    processing-routing-key: video.processing.request
    result-queue: video.processing.result.queue
    result-routing-key: video.processing.result
    processing-dlq: video.processing.dlq
    exchange: video.processing.exchange

  video:
    frames-fps: 30

  ffmpeg:
    path: ffmpeg

  storage:
    local-path: ${LOCAL_STORAGE_PATH:/tmp/zips}
    base-url: ""
