name: Docker Image Build and Publish to Docker Hub

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  STORAGE_LIB_REPO_TOKEN: ${{ secrets.STORAGE_LIB_REPO_TOKEN || github.token }}
  STORAGE_LIB_REPO: ${{ vars.STORAGE_LIB_REPO || 'FIAP-SOAT-G129/hackathon-storage-lib-fase5' }}
  STORAGE_LIB_REF: ${{ vars.STORAGE_LIB_REF || 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout storage lib
        uses: actions/checkout@v4
        with:
          repository: ${{ env.STORAGE_LIB_REPO }}
          ref: ${{ env.STORAGE_LIB_REF }}
          token: ${{ env.STORAGE_LIB_REPO_TOKEN }}
          path: _deps/storage-lib

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repository }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repository }}:${{ github.sha }}
